configfile: "config/config.yaml"


rule all:
    input:
        # 'results/SRA.feather',
        'results/metadata.csv'


rule query_ncbi:
    """
    Download or use already present NCBI SRA database dump to 
    query for SRA samples
    """
    output:
        feather_file = "results/SRA.feather"
    params:
        database = config['database'],
        taxon = config['taxon_id']
    conda: "envs/Renv.yml"
    log: "logs/query_ncbi.log"
    threads: 1
    shell:
        r'''
        (workflow/scripts/retrieve_NCBI_metadata.R \
            --database {params.database} \
            --taxon_id {params.taxon} \
            --output {output.feather_file}) >{log} 2>&1
        '''


rule wrangle_metadata:
    """
    Wrangles metadata from NCBI so that all runs have a isolation source
    geolocation and collection date.
    """
    input:
        feather_file = rules.query_ncbi.output.feather_file
    output:
        metadata = 'results/metadata.csv',
        clean_tsv = 'results/clean_tsv.tsv'
    conda: "envs/NCBI_metadata_notebook.yml"
    threads: 1
    log: notebook="logs/processed_notebook.ipynb"
    notebook: "notebooks/wrangle_NCBI_metadata.py.ipynb"
    # log: "logs/wrangle_ncbi_metadata.log"
    # shell:
    #     '''
    #     (papermill workflow/notebooks/wrangle_NCBI_metadata.py.ipynb \
    #         -p file_path {input.feather_file} \
    #         -p illumina_out {output.illumina} \
    #         -p nanopore_out {output.nanopore} \
    #         -p pacbio_out {output.pacbio}) >{log} 2>&1
    #     '''

rule download_files:
    """
    Downloads FASTA / FASTQ files for ID's collected in wrangle_metadata with SRAtools
    """
    input:
        metadata = rules.wrangle_metadata.output.clean_tsv
    params:
        download_dir = "results/SRA_downloads",
        platform = "ILLUMINA"
    output: "results/SRA_downloads/done.txt"
    conda: "envs/"
    threads: 6
    log: "logs/download_files.log"
    shell:
        '''
        (bash workflow/scripts/download_sra_files.sh \
            -f {input.metadata} \
            -o {params.download_dir} \
            -p {params.platform}
        ) >{log} 2>&1'''
